version: "3.8"

services:
    logprompt-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./models:/app/models
            - ./logs:/app/logs
        environment:
            - PYTHONPATH=/app
            - TRANSFORMERS_CACHE=/app/models
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # Optional: Add nginx for load balancing if needed
    # nginx:
    #   image: nginx:alpine
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf
    #   depends_on:
    #     - logprompt-api
